<a href="https://colab.research.google.com/github/DmitryPischik/Python_course_hw_10/blob/main/home_work_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd
import random

In [27]:
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

  whoAmI
0  robot
1  robot
2  robot
3  robot
4  human

In [28]:
unique_values = data['whoAmI'].unique()
unique_values

array(['robot', 'human'], dtype=object)

In [29]:
for value in unique_values:
    data[f'I_am_{value}'] = data['whoAmI'].apply(lambda x: 1 if x == value else 0)
data.head()

  whoAmI  I_am_robot  I_am_human
0  robot           1           0
1  robot           1           0
2  robot           1           0
3  robot           1           0
4  human           0           1

In [30]:
data.drop(data.columns[[len(unique_values)]], axis=1, inplace=True)
data.head()

  whoAmI  I_am_robot
0  robot           1
1  robot           1
2  robot           1
3  robot           1
4  human           0